Add solution for 6-module 1-task
js-tasks-ru/nodejs-20210618_atsvetkova7 pull request #10
Opened 2021-07-14 08:35 UTC by atsvetkova7

2021-07-14 08:36 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-07-16 11:53 UTC, tadjik1 commented on 06-koajs/01-chat-app/app.js
> +    });
небольшой нюанс: надо очищать массив `subscribers`, иначе в нем будут оставаться клиенты, запросы которых уже завершены

2021-07-16 11:54 UTC, tadjik1 requested changes
@atsvetkova7  отличная работа, хорошая реализация! небольшой совсем нюанс надо поправить по очистке массива клиентов, в остальном все хорошо

2021-07-16 13:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2021-07-16 14:47 UTC, tadjik1 approved these changes
👍

2021-07-16 14:47 UTC, merged